@startuml
autonumber
skinparam defaultFontName Courier
skinparam monochrome true
Begin->ZygoteInit:main()
ZygoteInit->RuntimeInit.MethodAndArgsCaller:run()
RuntimeInit.MethodAndArgsCaller->Method:invoke()
Method->ActivityThread:main()
ActivityThread->Looper:loop()
Looper->MessageQueue:next()
MessageQueue->MessageQueue:nativePollOnce()
MessageQueue->InputEventSender:dispatchInputEventFinished()
InputEventSender->InputMethodManager.ImeInputEventSender:onInputEventFinished()
InputMethodManager.ImeInputEventSender->InputMethodManager:finishedInputEvent()
InputMethodManager->InputMethodManager:invokeFinishedInputEventCallback()
InputMethodManager->InputMethodManager.PendingEvent:run()
InputMethodManager.PendingEvent->ViewRootImpl.ImeInputStage:onFinishedInputEvent()
ViewRootImpl.ImeInputStage->ViewRootImpl.AsyncInputStage:forward()
ViewRootImpl.AsyncInputStage->ViewRootImpl.InputStage:forward()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:onDeliverToNext()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:deliver()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:apply()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:forward()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:onDeliverToNext()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:deliver()
ViewRootImpl.InputStage->ViewRootImpl.AsyncInputStage:apply()
ViewRootImpl.AsyncInputStage->ViewRootImpl.InputStage:apply()
ViewRootImpl.InputStage->ViewRootImpl.AsyncInputStage:forward()
ViewRootImpl.AsyncInputStage->ViewRootImpl.InputStage:forward()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:onDeliverToNext()
ViewRootImpl.InputStage->ViewRootImpl.InputStage:deliver()
ViewRootImpl.InputStage->ViewRootImpl.ViewPostImeInputStage:onProcess()
ViewRootImpl.ViewPostImeInputStage->ViewRootImpl.ViewPostImeInputStage:processKeyEvent()
ViewRootImpl.ViewPostImeInputStage->DecorView:dispatchKeyEvent()
DecorView->Activity:dispatchKeyEvent()
Activity->KeyEvent:dispatch()
KeyEvent->Activity:onKeyUp()
Activity->FrameworkActivity:onBackPressed()
@enduml